"""Tipos de evento internos del controlador de movimiento."""

INICIO = 'INICIO'
CRUCE = 'CRUCE'
GIRO = 'GIRO'
DEAD_END = 'DEAD_END'
COLISION = 'COLISION'
PARE_DETECTADO = 'PARE_DETECTADO'
PARE_RESPETADO = 'PARE_RESPETADO'
PARE_FALSO = 'PARE_FALSO'
CELDA_AVANZADA = 'CELDA_AVANZADA'
META = 'META'
TIMEOUT = 'TIMEOUT'
